# Generated by Django 4.2.1 on 2023-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=350, null=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1, verbose_name='Priority')),
                ('complete', models.BooleanField(default=False, verbose_name='Complete')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name_plural': 'My Tasks',
                'ordering': ['created_at'],
            },
        ),
    ]
